//! Agent Telemetry Native Proxying Registry
//!
//! Stores temporary mappings between an IDE's trajectory UUID and the OAuth `access_token` / `project_id`
//! used by our reverse proxy pool for that generation session.
//!
//! When the MITM proxy subsequently intercepts the IDE's native `recordTrajectoryAnalytics` or
//! `recordCodeAssistMetrics` dumps, it looks up the Trajectory UUID here to rewrite the `Authorization`
//! and `project` payload fields. This ensures all native, massive Agent traces are impeccably attributed
//! to the exact proxy account that served them (solving duplicate/orphan traces).

use dashmap::DashMap;
use std::sync::OnceLock;
use std::time::{Duration, Instant};

/// Holds the proxy account information required to rewrite native telemetry.
#[derive(Clone, Debug)]
pub struct TelemetryTokenProxy {
    pub access_token: String,
    pub project_id: String,
    pub account_id: String,
    pub created_at: Instant,
}

pub struct TelemetryRegistry {
    /// Maps generic trajectory_uuid (or sessionId) to the assigned proxy credentials.
    map: DashMap<String, TelemetryTokenProxy>,
}

impl TelemetryRegistry {
    /// Get the global thread-safe registry singleton.
    pub fn global() -> &'static Self {
        static REGISTRY: OnceLock<TelemetryRegistry> = OnceLock::new();
        REGISTRY.get_or_init(|| TelemetryRegistry {
            map: DashMap::new(),
        })
    }

    /// Register a new trajectory UUID generated by the Go LS, mapping it to the proxy account's token.
    pub fn register(
        &self,
        trajectory_uuid: String,
        access_token: String,
        project_id: String,
        account_id: String,
    ) {
        // Simple garbage collection to prevent DashMap from growing indefinitely
        if self.map.len() > 100 {
            self.cleanup_old();
        }

        self.map.insert(
            trajectory_uuid,
            TelemetryTokenProxy {
                access_token,
                project_id,
                account_id,
                created_at: Instant::now(),
            },
        );
    }

    /// Lookup proxy credentials by trajectory ID.
    pub fn get(&self, trajectory_uuid: &str) -> Option<TelemetryTokenProxy> {
        self.map.get(trajectory_uuid).map(|r| r.value().clone())
    }

    /// Remove old entries (older than 10 minutes).
    /// Typically, telemetry is sent within a few seconds of stream completion.
    fn cleanup_old(&self) {
        let now = Instant::now();
        let max_age = Duration::from_secs(600); // 10 minutes
        self.map.retain(|_, v| now.duration_since(v.created_at) < max_age);
    }
}

/// Extract trajectory UUID from a wrapper requestId string.
/// Format: "agent/{timestamp_ms}/{trajectory_uuid}/{sequence_number}"
/// Returns the UUID component or "unknown" if parsing fails.
pub fn extract_trajectory_uuid(request_id: Option<&str>) -> String {
    request_id
        .and_then(|rid| rid.split('/').nth(2))
        .unwrap_or("unknown")
        .to_string()
}
